---
- name: Log Folder Housekeeping for Wildfly
  hosts: all
  become: yes
  vars:
    log_folder: "/opt/wildfly/wildfly-29.0.0.Final/standalone/log/"
    days_to_keep: 1

  tasks:
    - name: Get old wildfly log files from --> {{ log_folder }} directory
      find:
        paths: "{{ log_folder }}"
        patterns: "*.log.*"
        age: "{{ days_to_keep }}d"
      register: old_log_files

    - name: Delete old log files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_log_files.files }}"
      when: old_log_files.matched > 0

    - name: Display list of log files deleted
      debug:
        var: old_log_files
      when: old_log_files.matched > 0
