---
- name: DR SwitchOver Check
  hosts: all
  become: true
  tasks:

    - name: Stop Wildlfy Service
      systemd:
        name: wildfly
        state: stopped
        daemon_reload: yes
        enabled: yes
    
    - name: Check Wildfly process
      shell: /opt/wildfly/wildfly-29.0.0.Final/bin/jboss-cli.sh -c command=':read-attribute(name=server-state)' | grep running
      register: wildfly_process
      ignore_errors: true

    - name: Check if Wildfly is running
      fail:
        msg: "Wildfly is not running  --> Prechecks FAILED"
      when: wildfly_process.rc != 0

    - name: Appication Precheck
      debug:
        msg: "Prechecks PASSED"
