---
- name: Terminate an EC2 instance
  hosts: localhost
  gather_facts: False
  tasks:
    - name: terminate
      amazon.aws.ec2_instance:
        state: absent
        region: "us-east-1"
        filters:
          instance-state-name: running
