---
- name: Create MySQL Table
  hosts: all
  become: yes
  vars:
    mysql_db_name: vishal-test-test
    mysql_user: root
    mysql_password: "@Jammu93@"
  pre_tasks:
    - name: Install pip
      yum:
        name: pip
        state: present
    - name: Install mysql client
      pip:
        name: pymysql
        state: present  
  tasks:
    - name: DB - {{ mysql_db_name }} creation Task
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
      register: db_creation_output

    - name: Copy sql script to target host
      ansible.builtin.copy:
        src: mysql_script.sql
        dest: /home/ansible
      
    - name: Insert Sample Data in to created DB - {{ mysql_db_name }}
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: import
        target: /home/ansible/mysql_script.sql
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"

