---
- name: Create MySQL Table
  hosts: all
  become: yes
  vars_prompt:
    - name: mysql_password
      prompt: Enter the MYSQL DB password
  vars:
    mysql_db_name: vishal
    mysql_table_name: demo_list
    mysql_user: root
  tasks:
    - name: Install MySQL Python package
      pip:
        name: MySQL-python
        state: present
    - name: Create MySQL Table
      community.mysql.mysql_db:
        name: "{{ mysql_db_name }}"
        state: table
        target: "{{ mysql_table_name }}"
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
