---
- name: Create MySQL Table
  hosts: all
  become: yes
  vars:
    mysql_db_name: vishal-test-test
    mysql_user: root
    mysql_password: "@Jammu93@"
  collections:
    - community.mysql
    
  tasks:
    - name: Install collection
      shell: "ls -l"
