---
- name: Create MySQL Table
  hosts: all
  become: yes
#  vars_prompt:
 #   - name: mysql_password
#      prompt: Enter the MYSQL DB password
  vars:
    mysql_db_name: vishal_aap_test
    mysql_table_name: demo_list
    mysql_user: root
    mysql_password: '@Jammu93@'
  tasks:
    - name: Install pip
      yum:
        name: pip
        state: present
    - name: Create new databases with names 'foo' and 'bar'
      mysql_db:
        name: demo-aap
        state: present
