---
- name: Create MySQL Table
  hosts: all
  become: yes
  vars:
    mysql_db_name: vishal-test-test
    mysql_user: root
    mysql_password: "@Jammu93@"
  tasks:
    - name: Create MySQL Database
      ansible.builtin.mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: "{{ mysql_user }}"
        login_password: "{{ mysql_password }}"
