---
- name: Create MySQL Table
  hosts: all
  become: yes
  vars:
    mysql_db_name: vishal-test-test
    mysql_user: root
    mysql_password: "@Jammu93@"
    
  tasks:
    - name: Install collection
      shell: "ansible-galaxy collection install community.mysql"
