---
- name: Restart WildFly JVM
  hosts: all
  gather_facts: no
  tasks:
    - name: Check if WildFly is running
      command: /opt/wildfly/bin/jboss-cli.sh --connect --command=":read-attribute(name=server-state)" | grep -q "running"
      register: wildfly_running
      ignore_errors: yes
      
    - name: Restart WildFly if hung
      when: wildfly_running.rc != 0
      become: yes
      shell: "/opt/wildfly/bin/jboss-cli.sh --connect --command=:shutdown(restart=true)"
      register: restart_result
      
    - name: Check if WildFly restarted successfully
      debug:
        var: restart_result
