---
- hosts: all
  become: true
  gather_facts: no
  vars:
    wildfly_version: "29.0.0.Final"
    wildfly_install_dir: "/opt/wildfly"
  tasks:
    - name: Check if WildFly is running
      shell: "{{ wildfly_install_dir }}/wildfly-{{ wildfly_version }}/bin/jboss-cli.sh --connect --command=':read-attribute(name=server-state)' | grep -q running"
      register: wildfly_running
      ignore_errors: yes

    - name: Check the WildFly running cmd result
      debug:
        var: wildfly_running
      
    - name: Restart the JVM if it's hung
      systemd:
        name: wildfly
        state: restarted
        daemon_reload: yes
        enabled: yes
      register: restart_result
      when: wildfly_running.rc != 0
      
    - name: Check if WildFly restarted successfully
      debug:
        var: restart_result
