---
- hosts: all
  become: true
  collections:
    - community.general
  vars:
    jboss_eap_version: "7.3.0"
    jboss_eap_install_dir: "/opt/jboss"
  tasks:
    - name: Install my_collection_name
      command: ansible-galaxy collection install community.general
      
    - name: Add JBoss EAP repository
      community.general.redhat_subscription:
        state: present
        username: vishal_jutta
        password: '@Jammu1993_2@'
        pool_ids:
          - 2c94c2e3890c6f900189638350ec3b9a

    - name: Install JBoss EAP
      yum:
        name: "jboss-eap{{ jboss_eap_version | replace('.', '') }}"
        state: present

    - name: Start and Enable JBoss EAP Service
      systemd:
        name: "jboss-eap{{ jboss_eap_version | replace('.', '') }}-standalone"
        state: started
        enabled: yes

    - name: Open necessary ports in firewall
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 8080/tcp
        - 9990/tcp

    - name: Ensure SELinux allows JBoss EAP ports
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
