---
- hosts: all
  become: true
  vars:
tomcat_version: 9.0.50

tomcat_download_url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.zip

tomcat_install_dir: /opt

tomcat_zipfile: “{{tomcat_install_dir}}/tomcat.zip"
  collections:
    - middleware_automation.jws
  tasks:
    - name: check if we are able to ssh
      shell:
         "whoami; cd /tmp ; ls -l"
      register: output
