---
- hosts: all
  become: true
  tasks:
    - name: Reload systemd and Start Wildlfy Service
      systemd:
        name: wildfly
        state: started
        daemon_reload: yes
        enabled: yes
      when:
        - action == "start"
        
  handlers:
    - name: Start the JVM
      listen: start
      systemd:
        name: wildfly
        state: started
        daemon_reload: yes
        enabled: yes
    - name: Stop the JVM
      listen: stop
      systemd:
        name: wildfly
        state: stopped
        daemon_reload: yes
        enabled: yes
    - name: Restart the JVM
      listen: restart
      systemd:
        name: wildfly
        state: restarted
        daemon_reload: yes
        enabled: yes
