---
- hosts: all
  become: true
  vars:
    wildfly_version: "29.0.0.Final"
    wildfly_install_dir: "/opt/wildfly"
  vars_files:
    - db_credentials.yml
  tasks:
    - name: Reload systemd and Start Wildlfy Service
      systemd:
        name: wildfly
        state: started
        daemon_reload: yes
        enabled: yes
      when:
        - action == "start"
        
    - name: Reload systemd and Stop Wildlfy Service
      systemd:
        name: wildfly
        state: stopped
        daemon_reload: yes
        enabled: yes
      when:
        - action == "stop"

    - name: Reload systemd and Re-Start Wildlfy Service
      systemd:
        name: wildfly
        state: restarted
        daemon_reload: yes
        enabled: yes
      when:
        - action == "restart"
        
    - name: Deploy Application and restart the Service to load the app on JVM
      get_url:
        url: 'http://csci.viu.ca/~barskym/teaching/DM2012/labs/LAB6/Lab6A.war'
        dest: "{{ wildfly_install_dir }}/wildfly-{{ wildfly_version }}/standalone/deployments/"
        validate_certs: false
        force: true
      register: result
      until: result.status_code == 200
      retries: 2
      delay: 5
      when:
        - action == "deploy"
    - name: Print Deploy app logs
      debug:
        var: result
        
    - name: Restart the JVM after Deployment
      systemd:
        name: wildfly
        state: restarted
        daemon_reload: yes
        enabled: yes
      when:
        - action == "deploy"
        - result.status_code == 200
