---
- hosts: all
  become: true
  vars:
    wildfly_version: "29.0.0.Final"
    wildfly_install_dir: "/opt/wildfly"
  tasks:
    - name: Reload systemd and Start Wildlfy Service
      systemd:
        name: wildfly
        state: started
        daemon_reload: yes
        enabled: yes
      when:
        - action == "start"
        
    - name: Reload systemd and Stop Wildlfy Service
      systemd:
        name: wildfly
        state: stopped
        daemon_reload: yes
        enabled: yes
      when:
        - action == "stop"

    - name: Reload systemd and Re-Start Wildlfy Service
      systemd:
        name: wildfly
        state: restarted
        daemon_reload: yes
        enabled: yes
      when:
        - action == "restart"
        
    - name: Deploy Application and restart the Service to load the app on JVM
      get_url:
        url: 'https://osdn.dl.osdn.net/pal/17479/helloworld.war'
        dest: "{{ wildfly_install_dir }}/wildfly-{{ wildfly_version }}/standalone/deployments/"
        validate_certs: false
      when:
        - action == "deploy"
      notify: deploy

  handlers:
    - name: Restart the JVM after Deployment
      listen: deploy
      systemd:
        name: wildfly
        state: restarted
        daemon_reload: yes
        enabled: yes
