---
- name: POSTGRES DB PLAYBOOK
  hosts: all
  become: yes
  vars:
    db_name: BALIC_POC
    query: ""
    script_name: ""
    rows_affected: 2
  vars_files:
    - db_credentials.yml
  pre_tasks:
    - name: Install pip
      yum:
        name: pip
        state: present
    - name: Install psycopg2-binary client
      pip:
        name: psycopg2-binary
        state: present  
  tasks:
    - name: Copy sql script to target host
      become_user: postgres
      ansible.builtin.copy:
        src: "{{ script_name }}"
        dest: /var/lib/pgsql
      when: script_name is defined
        
    - name: Create a PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        state: present
      register: db_result

    - name: Print DB - {{ db_name }} creation output
      debug:
        var: db_result

    - name: RUN QUERY in DB - {{ db_name }}
      become_user: postgres
      postgresql_query:
        db: "{{ db_name }}"
        query:
        - "{{ query }}"
        - INSERT INTO balic_table (message) VALUES ('my_long_story2')
        - INSERT INTO balic_table (message) VALUES ('my_long_story3')
      register: db_result_op
      failed_when: db_result_op.rowcount != {{ rows_affected }}
      when: query is defined

    - name: PRINT Query Output
      debug:
        var: db_result_op.rowcount

    - name: RUN SCRIPT in DB - {{ db_name }}
      become_user: postgres
      community.postgresql.postgresql_script:
        db: "{{ db_name }}"
        path: "/var/lib/pgsql/{{ script_name }}"
      register: db_result_op_script
      failed_when: db_result_op_script.rowcount != {{ rows_affected }}
      when: script_name is defined

    - name: Print Script Output
      debug:
        var: db_result_op_script.rowcount
