---
- name: POSTGRES DB PLAYBOOK
  hosts: all
  become: yes
  vars:
    db_name: balic_poc
    query: ""
    script_name: ""
    rows_affected: ""
  vars_files:
    - db_credentials.yml
  pre_tasks:
    - name: Install pip
      yum:
        name: pip
        state: present
    - name: Install psycopg2-binary client
      pip:
        name: psycopg2-binary
        state: present  
  tasks:
    - name: Copy sql script to target host
      become_user: postgres
      ansible.builtin.copy:
        src: "{{ script_name }}"
        dest: /var/lib/pgsql
      when: script_name is defined and script_name != ''
        
    - name: Create a PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: "{{ db_name }}"
        state: present
      register: db_result

    - name: Print DB - {{ db_name }} creation output
      debug:
        var: db_result

    - name: RUN QUERY in DB - {{ db_name }}
      become_user: postgres
      postgresql_query:
        db: "{{ db_name }}"
        query:
        - "{{ query }}"
      register: db_result_op
      failed_when: db_result_op.rowcount != {{ rows_affected }}
      when: query is defined and query != ''

    - name: PRINT Query Output
      debug:
        var: db_result_op.rowcount
      when: query is defined and query != ''

    - name: RUN SCRIPT in DB - {{ db_name }}
      become_user: postgres
      community.postgresql.postgresql_script:
        db: "{{ db_name }}"
        path: "/var/lib/pgsql/{{ script_name }}"
      register: db_result_op_script
      failed_when: db_result_op_script.rowcount != {{ rows_affected }}
      when: script_name is defined and script_name != ''

    - name: Print Script Output
      debug:
        var: db_result_op_script.rowcount
      when: script_name is defined and script_name != ''

    - name: Exec some sql script
      become_user: postgres
      command: "psql -d {{ db_name }} -c 'BEGIN;'"
      register: op

    - name: RUN SCRIPT in DB again - {{ db_name }}
      become_user: postgres
      command: "psql -d {{ db_name }} -f '/var/lib/pgsql/{{ script_name }}'"
      register: db_result_op_script
      when: script_name is defined and script_name != '' and op.rc == 0

    - name: Commit
      become_user: postgres
      command: "psql -d {{ db_name }} -c 'COMMIT;'"
      register: op1
      when: db_result_op_script.rc == 0 and script_name is defined and script_name != '' and op.rc == 0 and db_result_op_script.stdout == "INSERT 0 {{ rows_affected }}"

    - name: Rollback
      become_user: postgres
      command: "psql -d {{ db_name }} -c 'ROLLBACK;'"
      register: op1
      when: db_result_op_script.rc != 0 and script_name is defined and script_name != '' and op.rc == 0 and db_result_op_script.stdout != "INSERT 0 {{ rows_affected }}"
      
