---
- name: Create MySQL Table
  hosts: all
  become: yes
  vars:
    mysql_db_name: BALIC_POC
    mysql_script_name: "mysql_script.sql"
    mysql_validatation_query: "SELECT COUNT(*) FROM balic_table;"
    rows_affected: 2
  vars_files:
    - db_credentials.yml
  pre_tasks:
    - name: Install pip
      yum:
        name: pip
        state: present
    - name: Install mysql client
      pip:
        name: psycopg2-binary
        state: present  
  tasks:
    - name: Create a PostgreSQL database
      become_user: postgres
      postgresql_db:
        name: mydb
        state: present
      register: db_result

    - name: Print PostgreSQL module output
      debug:
        var: db_result

    - name: Insert in to postgres db
      become_user: postgres
      postgresql_query:
        db: mydb
        query:
        - INSERT INTO balic_table (message) VALUES ('my_long_story')
        - INSERT INTO balic_table (message) VALUES ('my_long_story2')
      register: db_result_op

    - name: Print PostgreSQL query
      debug:
        var: db_result_op
