---
- hosts: localhost
  become: yes
  tasks:
    - name: read the excel file
      read_csv:
        path: file1.xls
      register: op
      delegate_to: localhost

    - name: print the op
      debug:
        msg: Value is {{ op }}
