---
- hosts: all
  become: yes
  tasks:
    - name: read the excel file
      read_csv:
        path: file1.csv
      register: values
      delegate_to: localhost
      
    - name: print the op
      debug:
        msg: Value is {{ item.HOSTNAME }}
      loop: "{{ values.list }}"
