---
- name: POSTGRES DB ROLLBACK PLAYBOOK
  hosts: all
  become: yes
  vars_files:
    - db_credentials.yml
  tasks:
    - name: Rollback
      become_user: postgres
      command: "psql -d {{ db_name }} -c 'delete from balic_table where id in (4,5,6);'"
      register: op1
