---
- name: POSTGRES DB COMMIT PLAYBOOK
  hosts: all
  become: yes
  vars_files:
    - db_credentials.yml
  tasks:
    - name: Copy rollback script to target host
      become_user: postgres
      ansible.builtin.copy:
        src: rollback.sql
        dest: /var/lib/pgsql
    - name: RUN Rollback in DB - {{ db_name }}
      become_user: postgres
      community.postgresql.postgresql_script:
        db: "{{ db_name }}"
        path: /var/lib/pgsql/rollback.sql
