---
- name: Install JBoss EAP Standalone on RHEL
  hosts: all
  become: true
  vars:
    jboss_eap_version: "8.0.0.Beta"
    jboss_eap_install_dir: "/opt/jboss"
  tasks:
    - name: Download JBoss EAP   https://developers.redhat.com/content-gateway/file/eap/8.4_Beta/jboss-eap-8.0.0.Beta.zip
      get_url:
        url: "ttps://developers.redhat.com/content-gateway/file/eap/8.4_Beta/jboss-eap{{ jboss_eap_version }}.zip"
        dest: "/tmp/jboss-eap{{ jboss_eap_version }}.zip"

    - name: Extract JBoss EAP
      ansible.builtin.unarchive:
        src: "/tmp/jboss-eap{{ jboss_eap_version }}.zip"
        dest: "{{ jboss_eap_install_dir }}"
        remote_src: yes
        creates: "{{ jboss_eap_install_dir }}/jboss-eap-{{ jboss_eap_version }}"

    - name: Create JBoss EAP Systemd Service File
      copy:
        content: |
          [Unit]
          Description=JBoss EAP Standalone Server
          After=network.target
          
          [Service]
          Type=simple
          ExecStart={{ jboss_eap_install_dir }}/jboss-eap-{{ jboss_eap_version }}/bin/standalone.sh -c standalone.xml
          ExecStop={{ jboss_eap_install_dir }}/jboss-eap-{{ jboss_eap_version }}/bin/jboss-cli.sh --connect command=:shutdown
          User=jboss
          Group=jboss
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
        dest: "/etc/systemd/system/jboss-eap.service"

    - name: Reload systemd and Start JBoss EAP Service
      systemd:
        name: jboss-eap
        state: started
        enabled: yes

    - name: Open necessary ports in firewall
      ansible.builtin.firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      loop:
        - 8080/tcp
        - 9990/tcp

    - name: Ensure SELinux allows JBoss EAP ports
      ansible.builtin.seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

  handlers:
    - name: Reload firewall
      ansible.builtin.firewalld:
        state: restarted
