---
- hosts: all
  #become: true
  tasks:
    - name: check if we are able to ssh
      shell:
         "ls -l; touch f1; ls -l; uptime"
      register: output
    - name: Print variable
      debug:
        msg: " Running playbook as user {{output}}"
