---
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: check if we are able to ssh
      shell:
         "ls -l; touch f2; ls -l; uptime"
      register: output
      
    - name: Print variable
      debug:
        msg: "Printing var {{output.stdout_lines}}"

    - name: Place logs in another remote server
      ansible.posix.synchronize:
        src: /home/ansible/f1
        dest: /home/ansible/logs
      delegate_to: localhost
