---
- hosts: all
  become: true
  gather_facts: no
  tasks:
    - name: check if we are able to ssh
      shell:
         "ls -l; touch f2; ls -l; uptime"
      register: output
      
    - name: Print variable
      debug:
        msg: "Printing var {{output.stdout_lines}}"

 #   - name: Synchronization of src on the inventory host to the dest on the localhost in pull mode
 #     ansible.posix.synchronize:
  #      mode: pull
 #       src: /tmp/log1/
 #       dest: /tmp/vish/logpulled
    - name: sync from src to dest
      ansible.posix.synchronize:
        src: /tmp/logtra/f4
        dest: /tmp/logpulled
