---
- hosts: all
  #become: true
  tasks:
    - name: check if we are able to ssh
      shell:
         "uptime"
      register: output
    - name: Print variable
      debug:
        msg: " Running playbook as user {{output}}"
