---
- name: Trigger Jenkins job remotely
  hosts: localhost
  gather_facts: no

  vars:
    jenkins_username: "vishal_jutta"
    jenkins_token: "admin"
    jenkins_job_name: "SBI_POC"
    jenkins_base_url: "http://192.168.29.57:8090"
    jenkins_trigger_token: "1119e7a2da9856b252f911fe0fcf540621"

  tasks:
    - name: Trigger Jenkins job
      uri:
        url: "{{ jenkins_base_url }}/job/{{ jenkins_job_name }}/build?token={{ jenkins_trigger_token }}"
        method: POST
        user: "{{ jenkins_username }}"
        password: "{{ jenkins_token }}"
        force_basic_auth: yes
        status_code: 201
      register: result

    - name: Check response
      debug:
        msg: "Job triggered successfully"
      when: result.status == 201
