---
- hosts: all
  become: true
  tasks:
    - name: Reload systemd and Start Wildlfy Service
      systemd:
        name: wildfly
        state: started
        daemon_reload: yes
        enabled: yes
      when:
        - action == "start"
        
    - name: Reload systemd and Stop Wildlfy Service
      systemd:
        name: wildfly
        state: stopped
        daemon_reload: yes
        enabled: yes
      when:
        - action == "stop"

    - name: Reload systemd and Re-Start Wildlfy Service
      systemd:
        name: wildfly
        state: restarted
        daemon_reload: yes
        enabled: yes
      when:
        - action == "restart"
